title = 'PsiBit Development'
baseURL = 'http://blog.psibitdev.com/'

theme = 'hugo-theme-shell'
languageCode = 'en-us'

[module]
  [module.hugoVersion]
    extended = true
    min = "v0.85.0"

[Params]
  # Note: This is for the meta description, which is different from the "description" displayed in the terminal.
  description = "Kevin Cefalu's Portfolio"

  [Params.Terminal]
  # Note: You can choose between the following color schemes:
  # Note: hugo-theme-shell: ["shell-powershell", "shell-ubuntu", "shell-retro"]
  # Note: gogh theme: https://mayccoll.github.io/Gogh/
  scheme = "Powershell"

  # Note: in terminal
  # [userName]@[pcName]:~/$ cd [workDir]
  # [userName]@[pcName]:~/[workDir]$ cat [profile]
  #
  # [description]
  #
  # Note: if you set Params.Tree > use = true
  # [userName]@[pcName]:~/[workDir]$ tree ./[folderName]/
  # ./[folderName]/
  # ...
  # Note: result of the tree command

  userName = "psibit"
  pcName = "stapp-blog-hugo"
  workDir = "src"
  profile = "profile.txt"

  # Note: speed at which text is displayed on the terminal
  # Note: if set to 0, typing animation will be disabled
  # Note: if you want to enable Mathjax, you need to set it to 0
  # Note: and set "math: true" at front matter in your Markdown file
  ps1Delay = 0 # prompt speed : [userName]@[pcName]:~/$ , [userName]@[pcName]:~/[workDir]$
  stdoutDelay = 0 # stdout speed : [description] , files in Params.Tree
  commandDelay = 50 # command speed : cd [workDir] , cat [profile] , tree ./[folderName]/

  # Note: speed at which text is displayed on the activity pages
  # Note: if set to 0, typing animation will be disabled
  # Note: if you want to enable Mathjax, you need to set it to 0
  # Note: and set "math: true" at front matter in your Markdown file
  titleDelay = 0 # title speed : "title" in front matter
  contentDelay = 0 # content speed : content in .md file

  # description = """
  # Hi, my name is Kevin Cefalu!
  # I also go by the handle PsiBit.
  # It's a pleasure to meet you!
  # """

  # Note: If you want to use a Markdown file, you can use the
  # following and put the description.md in /content/description.md
  description = "/description.md"

  [Params.Tree]
  use = true
  folderName = "projects"
  # Note: ["ACTIVITY", "URL or PATH TO YOUR MARKDOWN FILE"]
  files = [
    ["PowerShell", "/post/some-activity.md"],
    ["Containerization", "/post/some-activity.md"],
    ["Random", "/post/some-activity.md"],
  ]