description = "PsiBit Development - Blog"

[Terminal]
# hugo-theme-shell: ["shell-powershell", "shell-ubuntu", "shell-retro", gogh theme name]
scheme = "shell-powershell"
userName = "psibit"
pcName = "stapp-blog-hugo"
workDir = "src"
profile = "profile.txt"

# if set to 0, typing animation will be disabled
# if you want to enable Mathjax, you need to set it to 0
# and set "math: true" at front matter in your Markdown file

# speed at which text is displayed on the terminal
ps1Delay = 0 # prompt speed
stdoutDelay = 0 # stdout speed
commandDelay = 50 # command speed

# speed at which text is displayed on the activity pages
titleDelay = 0 # title speed
contentDelay = 0 # content speed

# Path relative to the localized content directory or string content
description = "/description.md" # or """ description """

[Tree]
use = true
folderName = "projects"
# ["ACTIVITY", "URL or PATH TO YOUR MARKDOWN FILE"]
files = [
  ["PowerShell", "/post/some-activity.md"],
  ["Containerization", "/post/some-activity.md"],
  ["Random", "/post/some-activity.md"],
]